on:
  repository_dispatch:
    types:
      - dependency_update # For Packagist Conductor
  schedule:
    - cron: '0 3 * * *'
  push:
    branches:
      - 'main'
      - 'master'
  issues:
    types:
      - edited

name: Utils

permissions:
  contents: write
  security-events: write
  pull-requests: write
  issues: write
  checks: write
  statuses: write
  packages: write

jobs:
  ci:
    name: Continuous Integration
    uses: WyriHaximus/github-workflows/.github/workflows/package-utils.yaml@run-renovate-on-github-actions
